### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by kellyabreu** [stefmolin/Watson-API#1]
Hello @stefmolin !
Could you help me , please?
I tried running docker-compose but it returned this error mensage:

$ docker-compose -f docker-compose.yml up
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 29, column 13
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 29, column 36

Must I create mongodb and rabbitmq repo on git and to set environment variable git_repo_url?

**Comment by stefmolin** [comment]
You will need to make a repo for each with a docker-compose file in each and put that url in place of `[git_repo_url]` for each.

**Comment by kellyabreu** [comment]
@stefmolin Tks!
